//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/cs_italy.html
halflife.wad
decals.wad
sprites/flare1.spr
cstrike.wad
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
models/scientist.mdl
itsitaly.wad
models/chick.mdl
sound/misc/killchicken.wav
models/winebottle.mdl
sound/ambience/opera.wav
sound/misc/sheep.wav
overviews/cs_italy.txt
overviews/cs_italy.bmp
maps/cs_italy.bsp
maps/cs_italy.txt
