//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/de_cbble.html
halflife.wad
overviews/de_cbble.txt
overviews/de_cbble.bmp
sound/ambience/sheep.wav
sound/ambience/cow.wav
sound/ambience/crow.wav
sound/ambience/sparrow.wav
cs_cbble.wad
cstrike.wad
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
maps/de_cbble.bsp
maps/de_cbble.txt
