//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/de_train_2x2.html
halflife.wad
sound/ambience/jetflyby1.wav
sprites/flare1.spr
sound/ambience/flies.wav
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
cs_bdog.wad
de_storm.wad
sound/ambience/wren1.wav
sound/ambience/tankidle1.wav
sound/ambience/boomer.wav
sound/ambience/dog6.wav
maps/de_train_2x2.bsp
